#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := hello-world

EXTRA_COMPONENT_DIRS := /home/user/myprojects/esp/esp-idf-lib/components

EXCLUDE_COMPONENTS := max7219 mcp23x17

include $(IDF_PATH)/make/project.mk
